apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: frisinn
    namespace: default
    labels:
        team: dusseldorf
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: /arbeid/inntektskompensasjon/health/isAlive
        initialDelay: 20
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: /arbeid/inntektskompensasjon/health/isReady
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://www-q0.nav.no/arbeid/inntektskompensasjon
        - https://frisinn.nais.oera-q.local
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    env:
        - name: APPRES_CMS_URL
          value: https://appres.nav.no
        - name: API_URL
          value: https://frisinn-api-q.nav.no
        - name: PUBLIC_PATH
          value: /arbeid/inntektskompensasjon
        - name: LOGIN_URL
          value: https://loginservice-q.nav.no/login?redirect=https://www-q0.nav.no/arbeid/inntektskompensasjon/soknad
        - name: APP_VERSION
          value: dev
        - name: PERSISTENCE
          value: "off"
        - name: APPSTATUS_PROJECT_ID
          value: "ryujtq87"
        - name: APPSTATUS_DATASET
          value: "staging"

